### ISSUE TITLE
ERROR: Could not pass event PlayerInteractEvent to MobArenaSigns v1.2.0

### ISSUE THREAD

**Issue by R3markable** [bittiez/MobArenaSigns#1]
The MobArenaSigns plugin seems to work very well on Spigot 1.12.2. Created join and exit signs work as intended, until the server restarts. After a restart the signs stop working and produce the following error:

> [14:57:38 ERROR]: Could not pass event PlayerInteractEvent to MobArenaSigns v1.2.0
> org.bukkit.event.EventException: null
> at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-R0.1-775423189fe-94b09808526-4f16bdbabba.jar:git-Spigot-7754231-94b0980]
> at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-R0.1-775423189fe-94b09808526-4f16bdbabba.jar:git-Spigot-7754231-94b0980]
> at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-R0.1-775423189fe-94b09808526-4f16bdbabba.jar:git-Spigot-7754231-94b0980]
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-R0.1-775423189fe-94b09808526-4f16bdbabba.jar:git-Spigot-7754231-94b0980]
> at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot-R0.1-775423189fe-94b09808526-4f16bdbabba.jar:git-Spigot-7754231-94b0980]
> at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [spigot-R0.1-775423189fe-94b09808526-4f16bdbabba.jar:git-Spigot-7754231-94b0980]
> at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951) [spigot-R0.1-775423189fe-94b09808526-4f16bdbabba.jar:git-Spigot-7754231-94b0980]
> at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-R0.1-775423189fe-94b09808526-4f16bdbabba.jar:git-Spigot-7754231-94b0980]
> at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-R0.1-775423189fe-94b09808526-4f16bdbabba.jar:git-Spigot-7754231-94b0980]
> at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-R0.1-775423189fe-94b09808526-4f16bdbabba.jar:git-Spigot-7754231-94b0980]
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
> at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
> at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-R0.1-775423189fe-94b09808526-4f16bdbabba.jar:git-Spigot-7754231-94b0980]
> at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-R0.1-775423189fe-94b09808526-4f16bdbabba.jar:git-Spigot-7754231-94b0980]
> at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-R0.1-775423189fe-94b09808526-4f16bdbabba.jar:git-Spigot-7754231-94b0980]
> at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-R0.1-775423189fe-94b09808526-4f16bdbabba.jar:git-Spigot-7754231-94b0980]
> at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-R0.1-775423189fe-94b09808526-4f16bdbabba.jar:git-Spigot-7754231-94b0980]
> at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
> Caused by: java.lang.NullPointerException
> at US.bittiez.MobArenaSigns.main.isMASSign(main.java:130) ~[?:?]
> at US.bittiez.MobArenaSigns.main.main(main.java:107) ~[?:?]
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
> at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
> at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-R0.1-775423189fe-94b09808526-4f16bdbabba.jar:git-Spigot-7754231-94b0980]
> ... 17 more

**Comment by bittiez** [comment]
I've looked through the code and I'm not sure why this was occuring, however because of how old this issue is I'm going to close this. If you still use this/the new version and run into this issue again please open a new issue, thank you.

**Comment by R3markable** [comment]
Well, thanks for looking into this..
I've stopped using the plugin about 2 years ago, because it didn't work.
